### ISSUE TITLE
Power limiting stopped working due to "powermeterfailure"

### ISSUE THREAD

**Issue by bmesuere** [thomase1234/esphome-fake-xemex-csmb#21]
Tonight, charging didn't work. Upon inspection, the wallbox reports "PowerMeterFailure" in its warnings.
The ESPhome part still runs fine, however I keep seeing `This is a lambda. address=0x4002, value=20802` in the logs. It thus seems that the wallbox initialization fails.

I will check all wiring tomorrow, but wanted to check if other people are encountering the same issue? Maybe Shell pushed an update that caused a change in behaviour.

**Comment by thomase1234** [comment]
I can confirm that my wall box still works fine.

**Comment by bmesuere** [comment]
I checked all wires and they were still fine. Did a hard reboot by cutting the power of both the esp32 and the wallbox (instead of a soft reboot yesterday) and everything seems to work again. 🤷
